- id: conformalize-repo
  name: conformalize-repo
  entry: action conformalize-repo
  language: python
  always_run: true
  pass_filenames: false
  description: Conformalize a repo
- id: format-requirements
  name: format-requirements
  entry: action format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml
  description: Format a set of requirements
- id: replace-sequence-strs
  name: replace-sequence-strs
  entry: action replace-sequence-strs
  language: python
  types: [python]
  description: Replace `Sequence[str]`
