- id: conformalize-repo
  name: conformalize-repo
  entry: action pre-commit conformalize-repo
  language: python
  always_run: true
  pass_filenames: false
  description: Conformalize a repo
- id: format-requirements
  name: format-requirements
  entry: action pre-commit format-requirements
  language: python
  types: [toml]
  files: pyproject\.toml
  description: Format a set of requirements
- id: replace-sequence-strs
  name: replace-sequence-strs
  entry: action pre-commit replace-sequence-strs
  language: python
  types: [python]
  description: Replace 'Sequence[str]' with 'list[str]'
- id: touch-empty-py
  name: touch-empty-py
  entry: action pre-commit touch-empty-py
  language: python
  types: [python]
  description: Touch empty '.py' files
